import { DataTypes, Model, Optional, Sequelize } from "sequelize";
import { sequelize } from "../sequelize";

export interface CategoryAttributes {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
}

type CategoryCreation = Optional<
  CategoryAttributes,
  "id" | "description" | "createdAt" | "updatedAt"
>;

class CategoryModel
  extends Model<CategoryAttributes, CategoryCreation>
  implements CategoryAttributes
{
  declare id: string;
  declare name: string;
  declare slug: string;
  declare description: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
  declare courses?: import("./course").Course[];
}

// Next's dev server (Turbopack/Fast Refresh) can re-evaluate this module
// while other already-loaded modules (e.g. the associations in src/db/index.ts)
// still reference the previous evaluation's class. Two different `Category`
// classes then fail Sequelize's `instanceof Model` checks. Caching on
// globalThis (matching src/db/sequelize.ts) keeps one instance per process.
const globalForCategoryModel = globalThis as unknown as { Category?: typeof CategoryModel };

export const Category = globalForCategoryModel.Category ?? CategoryModel;
// The class name doubles as an instance type in TypeScript; re-declare that
// here since `Category` above is a `const` binding, not the class declaration.
export type Category = InstanceType<typeof CategoryModel>;

if (!globalForCategoryModel.Category) {
  globalForCategoryModel.Category = Category;

  Category.init(
    {
      id: {
        // Generated by Postgres (gen_random_uuid(), via pgcrypto), not client-side JS -
        // the literal keeps the DEFAULT as raw SQL instead of a JS-computed value.
        type: DataTypes.UUID,
        defaultValue: Sequelize.literal("gen_random_uuid()"),
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      slug: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      description: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      createdAt: { type: DataTypes.DATE, allowNull: false },
      updatedAt: { type: DataTypes.DATE, allowNull: false },
    },
    {
      sequelize,
      tableName: "Category",
      modelName: "Category",
      timestamps: true,
    },
  );
}
