import { DataTypes, Model, Optional, Sequelize } from "sequelize";
import { sequelize } from "../sequelize";

export interface CategoryAttributes {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
}

type CategoryCreation = Optional<
  CategoryAttributes,
  "id" | "description" | "createdAt" | "updatedAt"
>;

class CategoryModel
  extends Model<CategoryAttributes, CategoryCreation>
  implements CategoryAttributes
{
  declare id: string;
  declare name: string;
  declare slug: string;
  declare description: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
  declare courses?: import("./course").Course[];
}

// Model identity must match the `Model` base class of the same sequelize
// instance, or Sequelize's `instanceof Model` checks fail when defining
// associations. `sequelize.models` is that instance's own registry, so it stays
// consistent both in dev (shared cached instance) and in a production build
// (one instance per module graph). A separate globalThis key would not: the
// sequelize instance is only cached outside production, so cached classes could
// outlive the `Model` they extend.

export const Category = (sequelize.models.Category as typeof CategoryModel | undefined) ?? CategoryModel;
// The class name doubles as an instance type in TypeScript; re-declare that
// here since `Category` above is a `const` binding, not the class declaration.
export type Category = InstanceType<typeof CategoryModel>;

if (!sequelize.models.Category) {

  Category.init(
    {
      id: {
        // Generated by Postgres (gen_random_uuid(), via pgcrypto), not client-side JS -
        // the literal keeps the DEFAULT as raw SQL instead of a JS-computed value.
        type: DataTypes.UUID,
        defaultValue: Sequelize.literal("gen_random_uuid()"),
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      slug: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      description: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      createdAt: { type: DataTypes.DATE, allowNull: false },
      updatedAt: { type: DataTypes.DATE, allowNull: false },
    },
    {
      sequelize,
      tableName: "Category",
      modelName: "Category",
      timestamps: true,
    },
  );
}
