import { DataTypes, Model, Optional, Sequelize } from "sequelize";
import { sequelize } from "../sequelize";

export interface CurriculumModule {
  /**
   * Stable identifier kept inside the JSONB so modules can be referenced
   * (anchor links, and a future promotion to a CourseModule table) without
   * depending on array position. Optional for rows seeded before it existed.
   */
  id?: string;
  title: string;
  topics: string[];
  /** Room to grow: modules may later carry their own prose, duration, lessons. */
  description?: string;
  duration?: string;
}

export interface Faq {
  q: string;
  a: string;
}

export interface CourseAttributes {
  id: string;
  slug: string;
  categoryId: string;
  title: string;
  description: string;
  shortDesc: string | null;
  contentMd: string;
  tools: string[];
  whoIsItFor: string[];
  skills: string[];
  curriculum: CurriculumModule[];
  faqs: Faq[];
  badge: string | null;
  color: string | null;
  students: number;
  duration: string;
  level: string;
  price: number;
  imageUrl: string | null;
  published: boolean;
  createdById: string | null;
  mentorId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

type CourseCreation = Optional<
  CourseAttributes,
  | "id"
  | "imageUrl"
  | "published"
  | "createdById"
  | "mentorId"
  | "createdAt"
  | "updatedAt"
  | "shortDesc"
  | "whoIsItFor"
  | "skills"
  | "curriculum"
  | "faqs"
  | "badge"
  | "color"
  | "students"
>;

class CourseModel extends Model<CourseAttributes, CourseCreation> implements CourseAttributes {
  declare id: string;
  declare slug: string;
  declare categoryId: string;
  declare title: string;
  declare description: string;
  declare shortDesc: string | null;
  declare contentMd: string;
  declare tools: string[];
  declare whoIsItFor: string[];
  declare skills: string[];
  declare curriculum: CurriculumModule[];
  declare faqs: Faq[];
  declare badge: string | null;
  declare color: string | null;
  declare students: number;
  declare duration: string;
  declare level: string;
  declare price: number;
  declare imageUrl: string | null;
  declare published: boolean;
  declare createdById: string | null;
  declare mentorId: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
  declare enrollments?: import("./enrollment").Enrollment[];
  declare category?: import("./category").Category;
  declare mentor?: import("./mentor").Mentor;
}

// Next's dev server (Turbopack/Fast Refresh) can re-evaluate this module
// while other already-loaded modules (e.g. the associations in src/db/index.ts)
// still reference the previous evaluation's class. Two different `Course`
// classes then fail Sequelize's `instanceof Model` checks. Caching on
// globalThis (matching src/db/sequelize.ts) keeps one instance per process.
const globalForCourseModel = globalThis as unknown as { Course?: typeof CourseModel };

export const Course = globalForCourseModel.Course ?? CourseModel;
// The class name doubles as an instance type in TypeScript; re-declare that
// here since `Course` above is a `const` binding, not the class declaration.
export type Course = InstanceType<typeof CourseModel>;

if (!globalForCourseModel.Course) {
  globalForCourseModel.Course = Course;

  Course.init(
    {
      id: {
        // Generated by Postgres (gen_random_uuid(), via pgcrypto), not client-side JS -
        // the literal keeps the DEFAULT as raw SQL instead of a JS-computed value.
        type: DataTypes.UUID,
        defaultValue: Sequelize.literal("gen_random_uuid()"),
        primaryKey: true,
      },
      slug: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      categoryId: {
        type: DataTypes.UUID,
        allowNull: false,
      },
      title: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      description: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      contentMd: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      shortDesc: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      tools: {
        type: DataTypes.ARRAY(DataTypes.STRING),
        allowNull: false,
        defaultValue: [],
      },
      // Flat lists mirror `tools` as TEXT[]; the nested shapes use JSONB.
      whoIsItFor: {
        type: DataTypes.ARRAY(DataTypes.TEXT),
        allowNull: false,
        defaultValue: [],
      },
      skills: {
        type: DataTypes.ARRAY(DataTypes.TEXT),
        allowNull: false,
        defaultValue: [],
      },
      curriculum: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: [],
      },
      faqs: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: [],
      },
      badge: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      color: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      students: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 0,
      },
      duration: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      level: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      price: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 0,
      },
      imageUrl: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      published: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
      },
      createdById: {
        type: DataTypes.UUID,
        allowNull: true,
      },
      mentorId: {
        type: DataTypes.UUID,
        allowNull: true,
      },
      createdAt: { type: DataTypes.DATE, allowNull: false },
      updatedAt: { type: DataTypes.DATE, allowNull: false },
    },
    {
      sequelize,
      tableName: "Course",
      modelName: "Course",
      timestamps: true,
    },
  );
}
