import { DataTypes, Model, Optional, Sequelize } from "sequelize";
import { sequelize } from "../sequelize";

export interface MentorAttributes {
  id: string;
  name: string;
  role: string;
  bio: string;
  photo: string | null;
  createdAt: Date;
  updatedAt: Date;
}

type MentorCreation = Optional<MentorAttributes, "id" | "photo" | "createdAt" | "updatedAt">;

class MentorModel extends Model<MentorAttributes, MentorCreation> implements MentorAttributes {
  declare id: string;
  declare name: string;
  declare role: string;
  declare bio: string;
  declare photo: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
  declare coursesMentored?: import("./course").Course[];
}

// Next's dev server (Turbopack/Fast Refresh) can re-evaluate this module
// while other already-loaded modules (e.g. the associations in src/db/index.ts)
// still reference the previous evaluation's class. Two different `Mentor`
// classes then fail Sequelize's `instanceof Model` checks. Caching on
// globalThis (matching src/db/sequelize.ts) keeps one instance per process.
const globalForMentorModel = globalThis as unknown as { Mentor?: typeof MentorModel };

export const Mentor = globalForMentorModel.Mentor ?? MentorModel;
// The class name doubles as an instance type in TypeScript; re-declare that
// here since `Mentor` above is a `const` binding, not the class declaration.
export type Mentor = InstanceType<typeof MentorModel>;

if (!globalForMentorModel.Mentor) {
  globalForMentorModel.Mentor = Mentor;

  Mentor.init(
    {
      id: {
        // Generated by Postgres (gen_random_uuid(), via pgcrypto), not client-side JS -
        // the literal keeps the DEFAULT as raw SQL instead of a JS-computed value.
        type: DataTypes.UUID,
        defaultValue: Sequelize.literal("gen_random_uuid()"),
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      role: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      bio: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      photo: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      createdAt: { type: DataTypes.DATE, allowNull: false },
      updatedAt: { type: DataTypes.DATE, allowNull: false },
    },
    {
      sequelize,
      tableName: "Mentor",
      modelName: "Mentor",
      timestamps: true,
    },
  );
}
