import { DataTypes, Model, Optional, Sequelize } from "sequelize";
import { sequelize } from "../sequelize";

export interface MentorAttributes {
  id: string;
  name: string;
  role: string;
  bio: string;
  photo: string | null;
  createdAt: Date;
  updatedAt: Date;
}

type MentorCreation = Optional<MentorAttributes, "id" | "photo" | "createdAt" | "updatedAt">;

class MentorModel extends Model<MentorAttributes, MentorCreation> implements MentorAttributes {
  declare id: string;
  declare name: string;
  declare role: string;
  declare bio: string;
  declare photo: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
  declare coursesMentored?: import("./course").Course[];
}

// Model identity must match the `Model` base class of the same sequelize
// instance, or Sequelize's `instanceof Model` checks fail when defining
// associations. `sequelize.models` is that instance's own registry, so it stays
// consistent both in dev (shared cached instance) and in a production build
// (one instance per module graph). A separate globalThis key would not: the
// sequelize instance is only cached outside production, so cached classes could
// outlive the `Model` they extend.

export const Mentor = (sequelize.models.Mentor as typeof MentorModel | undefined) ?? MentorModel;
// The class name doubles as an instance type in TypeScript; re-declare that
// here since `Mentor` above is a `const` binding, not the class declaration.
export type Mentor = InstanceType<typeof MentorModel>;

if (!sequelize.models.Mentor) {

  Mentor.init(
    {
      id: {
        // Generated by Postgres (gen_random_uuid(), via pgcrypto), not client-side JS -
        // the literal keeps the DEFAULT as raw SQL instead of a JS-computed value.
        type: DataTypes.UUID,
        defaultValue: Sequelize.literal("gen_random_uuid()"),
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      role: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      bio: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      photo: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      createdAt: { type: DataTypes.DATE, allowNull: false },
      updatedAt: { type: DataTypes.DATE, allowNull: false },
    },
    {
      sequelize,
      tableName: "Mentor",
      modelName: "Mentor",
      timestamps: true,
    },
  );
}
